### ISSUE TITLE
Doesn't work on localhost self signed SSL cert (1.8.13.0)

### ISSUE THREAD

**Issue by philjones88** [mwrock/RequestReduce#170]
As per title, using RR on my localhost development IIS (full) server with a SSL self signed certificate.

RR version: 1.8.13.0

These are the errors the dashboard records:

Key: 886c8e90-6265-0f36-76b1-a2ec55fac4a0
    First errored on: 18/04/2012 14:07:30
    Number: 1
    Exception #1: There were errors reducing https://localhost/static/js/jquery-1.6.4.min.js::https://localhost/static/js/jquery-ui-1.8.16.custom.min.js::https://localhost/static/js/jquery.cycle.js::https://localhost/static/js/superfish.js::https://localhost/static/js/hoverIntent.js::https://localhost/static/js/jquery.jElementExpander.js::https://localhost/static/js/jquery.form-2.63.js::https://localhost/static/js/knockout-2.0.0.js::https://localhost/static/js/jquery.meow.js::https://localhost/static/js/startup.js::
    Exception #2: RequestReduce had problems accessing https://localhost/static/js/jquery-1.6.4.min.js. Error Message from WebClient is: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
    Stack Trace#2:

   at RequestReduce.Utilities.WebClientWrapper.Download(String url, IEnumerable`1 requiredMimeTypes) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 89
   at RequestReduce.Utilities.WebClientWrapper.Download[T](String url) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 35
   at RequestReduce.Reducer.JavaScriptReducer.ProcessJavaScript(String url) in c:\RequestReduce\RequestReduce\Reducer\JavaScriptReducer.cs:line 56
   at RequestReduce.Reducer.JavaScriptReducer.ProcessResource(Guid key, IEnumerable`1 urls) in c:\RequestReduce\RequestReduce\Reducer\JavaScriptReducer.cs:line 32
   at RequestReduce.Reducer.HeadResourceReducerBase`1.Process(Guid key, String urls) in c:\RequestReduce\RequestReduce\Reducer\HeadResourceReducerBase.cs:line 37
   at RequestReduce.Module.ReducingQueue.ProcessQueuedItem() in c:\RequestReduce\RequestReduce\Module\ReducingQueue.cs:line 162

```
Exception #3: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Stack Trace#3:
```

   at System.Net.HttpWebRequest.GetResponse()
   at RequestReduce.Utilities.WebClientWrapper.Download(String url, IEnumerable`1 requiredMimeTypes) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 62

```
Exception #4: The remote certificate is invalid according to the validation procedure.
Stack Trace#4:
```

   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)

Key: dd1c5b4c-c20a-d2af-3e70-acc8890bfeae
    First errored on: 18/04/2012 14:07:30
    Number: 1
    Exception #1: There were errors reducing https://localhost/static/css/reset.css::https://localhost/static/css/text.css::https://localhost/static/css/grid.css::https://localhost/static/css/jquery-ui-1.8.16.custom.css::https://localhost/static/css/superfish.css::https://localhost/static/css/jquery.meow.css::https://localhost/static/css/site.css::
    Exception #2: RequestReduce had problems accessing https://localhost/static/css/reset.css. Error Message from WebClient is: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
    Stack Trace#2:

   at RequestReduce.Utilities.WebClientWrapper.Download(String url, IEnumerable`1 requiredMimeTypes) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 89
   at RequestReduce.Utilities.WebClientWrapper.Download[T](String url) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 35
   at RequestReduce.Utilities.WebClientWrapper.DownloadString[T](String url) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 114
   at RequestReduce.Reducer.CssReducer.ProcessCss(String url) in c:\RequestReduce\RequestReduce\Reducer\CssReducer.cs:line 51
   at RequestReduce.Reducer.CssReducer.ProcessResource(Guid key, IEnumerable`1 urls) in c:\RequestReduce\RequestReduce\Reducer\CssReducer.cs:line 36
   at RequestReduce.Reducer.HeadResourceReducerBase`1.Process(Guid key, String urls) in c:\RequestReduce\RequestReduce\Reducer\HeadResourceReducerBase.cs:line 37
   at RequestReduce.Module.ReducingQueue.ProcessQueuedItem() in c:\RequestReduce\RequestReduce\Module\ReducingQueue.cs:line 162

```
Exception #3: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Stack Trace#3:
```

   at System.Net.HttpWebRequest.GetResponse()
   at RequestReduce.Utilities.WebClientWrapper.Download(String url, IEnumerable`1 requiredMimeTypes) in c:\RequestReduce\RequestReduce\Utilities\WebClientWrapper.cs:line 62

```
Exception #4: The remote certificate is invalid according to the validation procedure.
Stack Trace#4:
```

   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)

**Comment by seanrockster** [comment]
I get an error from your ps script, the module utilities could not be loaded.
